[package]
name = 'learn_wgpu'
version = '0.1.0'
authors = ['IceSentry <c.giguere42@gmail.com>']
edition = '2018'
resolver = "2"

[dependencies]
wgpu = "0.11"
env_logger = "0.9"
winit = "0.25.0"
futures = "0.3.17"
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false, features = [
    "bevy_winit",
] }
log = "0.4"
