[package]
name = 'learn_wgpu'
version = '0.1.0'
authors = ['IceSentry <c.giguere42@gmail.com>']
edition = '2018'

[dependencies]
image = '0.23.4'
winit = '0.22.1'
futures = '0.3.4'

[dependencies.wgpu]
version = '0.5.0'
features = ['vulkan']
