[package]
name = 'learn_wgpu'
version = '0.1.0'
authors = ['IceSentry <c.giguere42@gmail.com>']
edition = '2018'
resolver = "2"

[dependencies]
wgpu = "0.11"
env_logger = "0.9"
winit = "0.25.0"
futures = "0.3.17"
tracing = { version = "0.1.29", features = ["log"] }
