[alias]
b = 'build'
br = 'build --release'
c = 'check'
t = 'test'
r = 'run'
rr = 'run --release'
space_example = [
    'run',
    '--release',
    '--',
    '"command list"',
]

[build]
rustflags = [
    '-C',
    'target-cpu=native',
]
